name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  VITE_STATSIG_CLIENT_KEY: client-80M5WR1Ip2EDokZuPzC7Rvbzu03xtcs2IeUWiQ9dsyk

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check files before build
        run: ls -R .  # List all files before build

      - name: Build project
        run: npm run build

      - name: Check files after build
        run: ls -R .  # List files after build to see where the output goes

      - name: Set up the build environment
        run: |
          # Ensure the build folder exists
          if [ -d "./dist" ]; then
            echo "dist folder exists."
          else
            echo "dist folder does not exist."
          fi
          
          # Create the dist folder if it doesn't exist, and add CNAME
          mkdir -p dist  # Ensure the dist folder exists
          echo 'scout.team987.com' > dist/CNAME  # Write the domain name to the CNAME file
          ls -R dist/  # List contents of dist/ to verify CNAME is created

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'  # Upload the dist folder (this path must be correct)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
